=== ChechuJR/Proyecto-Asir/DTD/SiteMap.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2013 (http://www.altova.com)-->
<!ELEMENT urlset ((url+))>
<!ATTLIST urlset
	xmlns CDATA #FIXED "http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation CDATA #IMPLIED
>
<!ELEMENT url ((loc, lastmod, priority))>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT loc (#PCDATA)>
<!ELEMENT lastmod (#PCDATA)>

=== ChechuJR/Proyecto-Asir/XML_XSL/sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE urlset SYSTEM "../DTD\SiteMap.dtd">
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!-- created with Free Online Sitemap Generator www.xml-sitemaps.com -->
	<url>
		<loc>https://www.realmadrid.com/</loc>
		<lastmod>2020-05-19T19:11:40+00:00</lastmod>
		<priority>1.00</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/sobre-el-real-madrid/el-club/patrocinadores</loc>
		<lastmod>2020-05-19T19:11:27+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas</loc>
		<lastmod>2020-05-19T19:11:28+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/castilla</loc>
		<lastmod>2020-05-19T19:14:20+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/baloncesto</loc>
		<lastmod>2020-05-19T19:14:21+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/tour-bernabeu</loc>
		<lastmod>2020-05-19T19:14:21+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/landing-gdpr</loc>
		<lastmod>2020-05-19T19:03:13+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/sobre-el-real-madrid/palmares/futbol</loc>
		<lastmod>2020-05-19T19:14:22+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/sobre-el-real-madrid/fundacion</loc>
		<lastmod>2020-05-19T19:14:26+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/registro</loc>
		<lastmod>2020-05-19T19:14:26+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/login</loc>
		<lastmod>2020-05-19T19:14:27+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/cs/Satellite?language=es&amp;pagename=RealMadridResponsive/Comunes/Logica/validarMadridistaSocio&amp;action=logout</loc>
		<lastmod>2020-05-19T19:14:27+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/en</loc>
		<lastmod>2020-05-19T19:09:42+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/fr</loc>
		<lastmod>2020-05-19T19:11:45+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/de</loc>
		<lastmod>2020-05-19T19:14:28+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/pt</loc>
		<lastmod>2020-05-19T19:14:28+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/ja</loc>
		<lastmod>2020-05-19T19:14:30+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/id</loc>
		<lastmod>2020-05-19T19:14:33+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/ar</loc>
		<lastmod>2020-05-19T19:14:33+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/baloncesto/abonos-temporada-1920</loc>
		<lastmod>2020-05-19T19:14:34+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/partidosfuera</loc>
		<lastmod>2020-05-19T19:14:36+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/faq</loc>
		<lastmod>2020-05-19T19:14:36+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip</loc>
		<lastmod>2020-05-19T19:14:37+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/partido-vip</loc>
		<lastmod>2020-05-19T19:14:41+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/temporada-vip</loc>
		<lastmod>2020-05-19T19:14:42+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/temporada-vip/palcos</loc>
		<lastmod>2020-05-19T19:14:43+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/temporada-vip/butacas</loc>
		<lastmod>2020-05-19T19:14:44+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/baloncesto-vip</loc>
		<lastmod>2020-05-19T19:14:45+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/faq</loc>
		<lastmod>2020-05-19T19:14:47+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/area-vip/contacto</loc>
		<lastmod>2020-05-19T19:14:48+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/tour-bernabeu/reserva-grupos</loc>
		<lastmod>2020-05-19T19:14:49+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/tour-bernabeu/tour-colegios</loc>
		<lastmod>2020-05-19T19:14:50+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/tour-bernabeu/tour-colegios/reserva-tu-visita</loc>
		<lastmod>2020-05-19T19:14:55+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/tour-bernabeu/tour-colegios/unidades-didacticas</loc>
		<lastmod>2020-05-19T19:14:56+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/planeta_blanco</loc>
		<lastmod>2020-05-19T19:14:57+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/entradas/tour-bernabeu/faq</loc>
		<lastmod>2020-05-19T19:14:58+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/aficion/madridistas/internacionales</loc>
		<lastmod>2020-05-19T19:03:13+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/estadio-santiago-bernabeu/tiendas</loc>
		<lastmod>2020-05-19T19:14:18+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol</loc>
		<lastmod>2020-05-19T19:14:59+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/partidos/calendario</loc>
		<lastmod>2020-05-19T19:13:16+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/clasificacion</loc>
		<lastmod>2020-05-19T19:15:00+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/noticias</loc>
		<lastmod>2020-05-19T19:10:50+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/videos</loc>
		<lastmod>2020-05-19T19:15:00+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/fotos</loc>
		<lastmod>2020-05-19T19:15:03+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/plantilla</loc>
		<lastmod>2020-05-19T19:14:22+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera</loc>
		<lastmod>2020-05-19T19:15:30+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/castilla</loc>
		<lastmod>2020-05-19T19:11:09+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/juvenil-a</loc>
		<lastmod>2020-05-19T19:15:32+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/juvenil-b</loc>
		<lastmod>2020-05-19T19:15:33+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/juvenil-c</loc>
		<lastmod>2020-05-19T19:15:34+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/cadete-a</loc>
		<lastmod>2020-05-19T19:11:57+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/cadete-b</loc>
		<lastmod>2020-05-19T19:11:25+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/infantil-a</loc>
		<lastmod>2020-05-19T19:15:35+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/infantil-b</loc>
		<lastmod>2020-05-19T19:15:36+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/alevin-a</loc>
		<lastmod>2020-05-19T19:15:14+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/alevin-b</loc>
		<lastmod>2020-05-19T19:15:38+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/benjamin-a</loc>
		<lastmod>2020-05-19T19:15:43+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/benjamin-b</loc>
		<lastmod>2020-05-19T19:15:45+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/prebenjamin</loc>
		<lastmod>2020-05-19T19:15:46+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/cantera/pruebas-acceso</loc>
		<lastmod>2020-05-19T19:15:31+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/futbol/veteranos</loc>
		<lastmod>2020-05-19T19:15:46+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/baloncesto</loc>
		<lastmod>2020-05-19T19:14:52+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/baloncesto/partidos/calendario</loc>
		<lastmod>2020-05-19T19:15:49+00:00</lastmod>
		<priority>0.80</priority>
	</url>
	<url>
		<loc>https://www.realmadrid.com/baloncesto/clasificacion</loc>
